ci: Add slack hook for CI failure (#46)
* ci: Add slack hook for CI failure

* fix indentation

diff --git a/.github/workflows/create-release.yml b/.github/workflows/create-release.yml
--- a/.github/workflows/create-release.yml
+++ b/.github/workflows/create-release.yml
@@ -80,3 +80,37 @@ jobs:
     with:
       upload_url: ${{ needs.create-release.outputs.upload_url }}
       date: ${{ needs.create-release.outputs.today }}
+
+  # Wait for results of called workflows
+  monitor-release-status:
+    needs: [ create-release, release-forc, release-fuel-core, release-forc-explorer, release-forc-wallet ]
+    runs-on: ubuntu-latest
+
+    steps:
+    - name: Ensure release-forc succeeded
+      run: |
+        if [ 
+          "${{ needs.create-release.result }}" != "success"
+          || "${{ needs.release-forc.result }}" != "success"
+          || "${{ needs.release-fuel-core.result }}" != "success"
+          || "${{ needs.release-forc-explorer.result }}" != "success"
+          || "${{ needs.release-forc-wallet }}" != "success"
+        ]; then
+          echo "Workflow failed. Exiting..."
+          exit 1
+        else
+          echo "All workflows succeeded."
+          exit 0
+        fi
+
+    - name: Notify if Job Fails
+      uses: ravsamhq/notify-slack-action@v1
+      with:
+        status: ${{ job.status }}
+        token: ${{ secrets.GITHUB_TOKEN }}
+        notification_title: "{workflow} has {status_message}"
+        message_format: "{emoji} *{workflow}* {status_message} in <{repo_url}|{repo}> : <{run_url}|View Run Results>"
+        footer: ""
+        notify_when: "failure"
+      env:
+        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_TOOLING }}
